### ISSUE TITLE
Review Cookie and Privacy Policy

### ISSUE THREAD

**Issue by juanbrits** [datopian/birmingham-city-observatory#27]
Are both the cookie and privacy policy needed for Birmingham?

**Comment by demenech** [comment]
@juanbrits I'm gonna be hiding both these pages, as we are not collecting any personal data nor using cookies.

**Comment by demenech** [comment]
PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/21

**Comment by demenech** [comment]
New PR: https://github.com/datopian/portal-birmingham-city-observatory/pull/38

@juanbrits , please note: 
- As we have a Terms and Conditions page, instead of having the links directly in the footer I added the links to this page:
![ss-2022-09-30-15:07:11](https://user-images.githubusercontent.com/16550934/193330688-54f2443a-b0f2-4bf9-9818-5ae7399c2096.png)
- We might not need the popup: https://umami.is/docs/faq
