### ISSUE TITLE
Activity stream tab isn’t working

### ISSUE THREAD

**Issue by Daniellappv** [datopian/birmingham-city-observatory#40]
## Links and Screenshots 

It's currently returning an application error

Eg. https://www.cityobservatory.birmingham.gov.uk/@birmingham-city-council/payments-to-suppliers-over-500

See 
<img width="1140" alt="Screenshot 2023-02-23 at 12 38 51" src="https://user-images.githubusercontent.com/45828069/220883806-c0474c6c-4b6f-4072-9af0-81594db0e8c8.png">

## Acceptance

* [x] Activity stream tab is working

**Comment by demenech** [comment]
Not working because the FE isn't able to fetch data about the users:
https://birmingham-city-observatory.datopian.com/api/3/action/user_show?id=849df43a-e91b-4613-8c99-ab9d53e48d4c -- Access denied
https://admin.opendatani.gov.uk/api/3/action/user_show?id=18755039-02c1-4a87-8a1e-eae048ba0def -- Works

We have to change the `public user details` setting in order to make that work (https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-auth-public-user-details).

Before proceeding with this, @Daniellappv I just want to make sure we really want to show the name of the users [like ODNI does](https://www.opendatani.gov.uk/@department-for-infrastructure-parking-enforcement-unit/penalty-charge-notice-data). The other option would be keeping the users anonymous, as done for Datahub:
![ss-2023-02-23-08:59:27](https://user-images.githubusercontent.com/16550934/220899990-037c34f0-bced-4f0c-aee3-5fe738458197.png)

**Comment by anuveyatsu** [comment]
@demenech this is because we need to hide user details as per GDPR etc. so makes sense to not mention usernames etc. I think saying "A user" is enough re activity stream.

**Comment by demenech** [comment]
**Commit**: https://github.com/datopian/portal-birmingham-city-observatory/commit/b346ef873b549d9b2f9bd462ad86f6ab0e005919 (forgot to change to a different branch, apologies)
**Deployed to prod:** https://birmingham-city-observatory-h7shj0vnv-datopian1.vercel.app/@birmingham-city-council/the-annual-education-performance-report-2019

**Comment by anuveyatsu** [comment]
FIXED:

<img width="1440" alt="Screen Shot 2023-09-12 at 4 52 48 PM" src="https://github.com/datopian/birmingham-city-observatory/assets/17809581/a8490c21-0d25-4885-81f9-d2f5e10297c6">
