### ISSUE TITLE
Redirects and announcement on the old site

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/birmingham-city-observatory#6]
## Tasks

- [ ] Setup redirects from old site to the new frontend
- [ ] Implement the banner with text: "Thanks for coming to the Birmingham City Factory. We are currently upgrading this old site, and the new platform will be re-launched as "Birmingham City Observatory" by October 2022."

**Comment by juanbrits** [comment]
DNS records for the frontend are pointing to: https://www.cityobservatory.birmingham.gov.uk/


The domain should point to the CKAN instance in our cloud: CNAME to [nginx-prod-lb.datopian.com](http://nginx-prod-lb.datopian.com/) .
It does look like the domain has been made accessible, however only on your private network.

The problem is that the frontend communicates with the backend via a public network. However we are able to restrict access to the admin site from our end as well as disable self-registration.
